Modify determineMouseOver to check SpellFlyout
PhenomDevel/BlizzHUDTweaks pull request #82
Opened 2024-09-07 23:49 UTC by markoleptic

2024-09-07 23:59 UTC, PhenomDevel commented on BlizzHUDTweaks/MouseoverFrameFading.lua
> +              return true
If we determine that a linked frame is being hovered over, we can return it immediately without having to possibly loop through all the other frames as well. Don't we?

2024-09-07 23:59 UTC, PhenomDevel commented on BlizzHUDTweaks/MouseoverFrameFading.lua
> +              linkedFrameMouseover = true
Same as above.

2024-09-08 00:00 UTC, PhenomDevel commented on BlizzHUDTweaks/MouseoverFrameFading.lua
> +  return linkedFrameMouseover or fallback
If we immediately  return when a frame/linked frame is determined to be hovered we only need to return the fallback or false

2024-09-08 00:00 UTC, PhenomDevel requested changes
Some small questions which when correct should be fixed.

2024-09-08 00:09 UTC, PhenomDevel commented on BlizzHUDTweaks/MouseoverFrameFading.lua
> +              return true
This comment was supposed to be on the line mentioned in the next comment, sorry for the confusion :D

2024-09-08 00:32 UTC, merged

2024-09-08 00:34 UTC, markoleptic commented
I tried doing early returns earlier when I was working on the fix, but somehow it caused things to break. However it seems to work fine now. Good suggestion!

2024-09-08 00:36 UTC, PhenomDevel commented
I could not find any strange behavior in my tests. I only tested with my mage though. Seems to work fine and is merged. Will be available in 1.49.4 soon.

Thanks for the PR :)